/*
 * This source file was generated by the Gradle 'init' task
 */

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import easy.RomanNumerals;

class RomanNumeralsSpec {

    RomanNumerals romanNumerals = new RomanNumerals();

    @Test
    void converts3999ToRoman() {
        assertEquals("MMMCMXCIX", romanNumerals.intToRoman(3999));
    }

    @Test
    void converts58ToRoman() {
        assertEquals("LVIII", romanNumerals.intToRoman(58));
    }

    @Test
    void converts4ToRoman() {
        assertEquals("IV", romanNumerals.intToRoman(4));
    }
}
